cargo-features = ["named-profiles"]

[package]
name = "blog_os"
version = "0.1.0"
authors = ["Jonathan Merritt <j.s.merritt@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
